semantic-release/npm

lib/get-last-release.js, test/get-last-release.test.js, test/helpers/mock-registry.js
=> feat: Use always-auth from .npmrc

lib/update-package-version.js, test/update-package-version.test.js
=> Preserve `package.json` and `npm-shrinkwrap.json` formatting

index.js, lib/verify-auth.js, lib/verify-config.js, test/integration.test.js, test/verify-config.test.js
Follow up to #12
See [comment](https://github.com/shroudedcode/semantic-release-apm/issues/4#issuecomment-353403804)
=> Skip npm auth verification if npmPublish is false

lib/get-pkg.js, test/get-pkg.test.js, test/integration.test.js
=> Verify `package.json` has a `version` property

index.js, lib/get-last-release.js, test/get-last-release.test.js, test/helpers/mock-registry.js, test/integration.test.js
Follow up to #26. I forgot to add the log message and the `ENOGITHEAD` error.
=> Add message if no gitHead found

index.js, test/integration.test.js
=>  fix: skip auth verification when skipping publish to registry

README.md, index.js, lib/prepare.js, lib/publish.js, test/integration.test.js
See semantic-release/semantic-release#649
=> feat: update package.json and create tarball in `prepare` hook

README.md, index.js, lib/publish.js, test/integration.test.js
=> feat: skip publising if the `package.json` `private` prop is `true`

README.md, lib/verify-config.js, package.json
child of semantic-release/semantic-release#936
=>  fix: use default value for `null` options + plugins option in documentation

package.json
=> fix(package): pin npm to 6.5.0

lib/prepare.js, test/prepare.test.js
=> fix: setting tarballDir to CWD causes fs-extra error

.travis.yml
=> Test in lowest suported node version

.travis.yml
=> Test in node 12

package.json
Updates the following dependencies:
- lodash
- npm
(The failing tests were failing before implementing these changes.)
=> fix(package): update vulnerable dependencies

README.md, lib/get-registry.js, test/get-registry.test.js
=> feat: allow to configure the registry via `NPM_CONFIG_REGISTRY`

lib/set-npmrc-auth.js, test/set-npmrc-auth.test.js
=> fix: preserve config in both home and local `.npmrc`

lib/add-channel.js, lib/definitions/errors.js, lib/publish.js, package.json, test/get-pkg.test.js, test/helpers/npm-registry.js, test/integration.test.js, test/set-npmrc-auth.test.js
=> chore(package): update xo to version 0.28.1

lib/definitions/errors.js
=> fix: improve error message text for npm tokens

README.md
took me a while finding the correct script hook was actually `postversion` :)
=> docs(readme): fix script suggestion

package-lock.json, package.json
Reverts semantic-release/npm#424
=> Revert "chore(deps): update dependency p-retry to v5"

package-lock.json, package.json
This reverts commit https://github.com/semantic-release/npm/commit/28265ec20bb230c4bb26f541508afb62272d5404.
=> fix(revert): "fix(deps): update dependency npm to v9"

.github/workflows/release.yml, package.json
from my experience so far, this should be all that is necessary. since we already have this beta in progress, we might as well try it here first.
=> ci(provenance): enabled provenance for publishing

package-lock.json, package.json
This PR removes `codecov` from the project following the notice from @tidelift on its cease of support.
https://github.com/semantic-release/semantic-release/issues/3425
=> test: remove `codecov`
