- index.js
- lib/publish.js
- lib/set-npmrc-auth.js
- lib/verify.js
- test/get-registry.test.js
- test/integration.test.js
- test/set-npmrc-auth.test.js
Pass registry URL to `npm` CLI with `--registry`.
The environment variable `npm_config_registry` takes precedence to the registry configured in `.npmrc` when running `npm` commands.
Yarn sets this variable to `https://registry.yarnpkg.com` creating an `EINVALIDNPMTOKEN` error when running `semantic-release` with Yarn.
Passing `--registry` with the value retrieved from `.npmrc` or `package.json` override the `npm_config_registry` set by Yarn.
Fix semantic-release/semantic-release#533
> Fix EINVALIDNPMTOKEN error with Yarn

- README.md
- index.js
- lib/set-legacy-token.js
- lib/set-npmrc-auth.js
- test/integration.test.js
- test/set-npmrc-auth.test.js
We are supporting legacy npm authentication as we use [npm-registry-couchapp](https://github.com/npm/npm-registry-couchapp) for integration tests which doesn't support token authentication.
But it wasn't intended to be used in production.
It seems there is several private npm registry solution that supports only legacy authentication.
See semantic-release/semantic-release#500 and #6.
This PR improve our support of the legacy auth and mention it in the documentation.
Fix semantic-release/semantic-release#500
> Support legacy authentication

- README.md
- index.js
- lib/publish.js
- lib/verify.js
- package.json
- test/integration.test.js
- test/verify.test.js
Add 2 new options:
- `npmPublish` can be set to `false` to skip the publishing on npm registry
- If `tarballDir` is set the npm tarball (`npm pack`) will be generated in the configured directory
That will allow to users who do not want to publish on the registry to still use the plugin to:
- Update the `package.json` and publish it with [git]([npm](https://github.com/semantic-release/git)) or [github]([npm](https://github.com/semantic-release/github))
- To generate the npm tarball and publish it as well
> Add `npmPublish` and `tarballDir` options

- README.md
- index.js
- lib/get-pkg.js
- lib/publish.js
- lib/update-package-version.js
- lib/verify.js
- package.json
- test/get-pkg.test.js
- test/integration.test.js
- test/update-package-version.test.js
- test/verify.test.js
Allow to publish from a sub-directory, similarly to `npm publish sub-dir`.
Fix semantic-release/semantic-release#570
> Add `pkgRoot` option to publish a sub-directory

- lib/get-last-release.js
- lib/get-version-head.js
- lib/git.js
- package.json
- test/get-version-head.test.js
- test/git.test.js
- test/helpers/git-utils.js
- test/integration.test.js
This is a port of a workaround for npm/read-package-json#77  implemented in the core when npm publishing was still part of it.
Now that we handle `npm` via plugin this npm specific workaround should be here.
In addition this will have to be used within this plugin to implement semantic-release/semantic-release#563
> Retrieve gitHead from git tag if it's missing from the npm metadata

- README.md
Closes #30.
Should I send a similar PR to the main semantic-release docs?
> doc: clarify npm 2FA supported level

- README.md
`condition-travis` is not required since semantic-release/semantic-release#578 was merged.
> Remove references to `condition-travis` from the doc

- lib/update-package-version.js
- test/update-package-version.test.js
See the reason for updating `package-lock.json` in this [comment](https://github.com/semantic-release/git/pull/23#issuecomment-360955388).
This PR also essentially revert #22 as updating the version via regexp turned out to not be such a great idea:
- Some edges cases are not covered, in particular if any configuration in `package.json` contains the keyword `"version"`
- Impossible to update the  `package-lock.json` as it contains `"version"` multiple time
The `package.json`, `package-lock.json` and `npm-shrinkwrap` are now formatted like `npm version` [does](https://github.com/npm/npm/blob/latest/lib/version.js#L200).
That might result in situation in which we change the user format, but I think it's acceptable as `npm version` or `npm install XXX` would change it the same way.
>  feat: update version in `package-lock.json`

- lib/publish.js
some packages, for example [`patch-package`](https://github.com/ds300/patch-package), can print output while `prepare` task, so in order to get right tarball name it's better to get only last line from stdout
> fix: get tarball name as last line from stdout

- lib/definitions/errors.js
- lib/set-npmrc-auth.js
- test/set-npmrc-auth.test.js
Fix error in https://travis-ci.org/crystal-lang-tools/atom-ide-crystal/builds/350548591#L1331
> fix: fix error handling when no npm token is defined

- lib/update-package-version.js
- package.json
- test/update-package-version.test.js
Fix #70
Inspired by https://github.com/npm/npm/blob/1365694bb3da9be95964a4eb6c92b1c71d0edde5/lib/install/save.js#L54 which use the same libs.
> feat: preserve indentation and newline type of package.json

- index.js
- lib/get-pkg.js
- lib/get-registry.js
- lib/get-release-info.js
- lib/prepare.js
- lib/publish.js
- lib/set-legacy-token.js
- lib/set-npmrc-auth.js
- lib/update-package-version.js
- lib/verify-auth.js
- package.json
- test/get-pkg.test.js
- test/get-registry.test.js
- test/get-release-info.test.js
- test/integration.test.js
- test/set-npmrc-auth.test.js
- test/update-package-version.test.js
BREAKING CHANGE: require `semantic-release` >= `15.8.0`
> feat: use `cwd` and `env` options passed by core

- lib/prepare.js
- lib/publish.js
- package.json
- test/integration.test.js
feat: add dependency to `npm`
The plugin will now use the npm version in its dependencies to run npm commands.
That allow to avoid bugs in outdated npm version. And Greenkeeper will automatically test the plugin for new npm releases.
feat: log npm CLI output to `stdout`/`stderr`
Will help to debug what's npm is doing when the plugin calls `npm pack` and `npm publish`, in particular regarding `prepack` and `prepublish` functions
>  feat: log npm CLI output to `stdout`/`stderr`

- index.js
- test/integration.test.js
Any npm command, include `npm version` attempts to exapand the `LEGACY_TOKEN` environment varialbe if it is set in `.npmrc`.
> fix: always attempt to set the legacy token env var

- package.json
To be merged once https://npm.community/t/npm-6-6-0-broke-authentication-with-npm-registry-couchapp/4752 is fixed.
Fix #134 
Fix #142
> fix(package): update npm to version 6.7.0

- lib/set-npmrc-auth.js
- test/set-npmrc-auth.test.js
This bug cost me weeks 😅
`npm` honors the `NPM_CONFIG_USERCONFIG` setting, which our CI relies on to inject shared credentials at runtime. `npm publish` succeeds if we're not using Semantic Release. However, `@semantic-release/npm` has reimplemented a credentials check in a manner not compatible with the way `npm` handles the user config environment variable. This PR checks the location specified in `NPM_CONFIG_USERCONFIG` before using `rc` to crawl up the file hierarchy.
It should be noted that `rc` does not fully implement the `.npmrc` resolution algorithm, skipping the ability to specify config files from an env var. That's why we're facing this problem.
I've tested this locally, and this small fix would allow us to use Semantic Release 🎉
> Honor NPM_CONFIG_USERCONFIG setting

- test/prepare.test.js
Some people have `package-lock=false` disabled in their global `~/.npmrc`, so for these tests to pass reliably, an `.npmrc` needs to be present in the test folder.
> test: write an .npmrc for package-lock related tests

- package.json
> fix: revert to execa `^1.0.0`

- index.js
- lib/get-release-info.js
- lib/prepare.js
- lib/publish.js
- lib/set-npmrc-auth.js
- lib/verify-auth.js
- package.json
- test/get-release-info.test.js
- test/integration.test.js
- test/prepare.test.js
- test/set-npmrc-auth.test.js
fix #145
Instead of modifying the local `.npmrc` the plugin now create a temporary one in the OS temp directory and all npm command specify that file with `--userconfig`.
Any config in a local `.npmrc` will be copied to the temporary one.
This avoid leaving a modified `.npmrc` file behind.
> feat: preserve local `.npmrc` file

- README.md
In the options table, the columns weren't matching so I've updated the markdown so there are only 2 columns. Was this intended or auto-formatted this way?
> docs(README): fix columns of options table in readme

- package.json
Hi, I made this PR to update the node version since when I tried the lowest version in the package, it throws an error for got dependency
```sh
error got@11.6.0: The engine "node" is incompatible with this module. Expected version ">=10.19.0". Got "10.18.1"
error Found incompatible module.
```
I also update npm dependency because the actual version has a subdependency in its treeDependency that give me a vulnerability issue detected from github.
Hope this could help.
> Updating node and npm version in package

- README.md
When "pkgRoot" is set the postpublish script will excute relativly to the pkgRoot. Hence cp dist/ will generate the error "No such file or directory"
> docs: Fix postpublish script when "pkgRoot":"dist"

- lib/verify-auth.js
- package.json
- test/helpers/npm-registry.js
npm upgrade is just to have the latest version. On the other hand, after npm install and npm audit, xo appears as a low vulnerability, so it recommends the actual version that it's set in this PR.
> Upgrade npm and xo dependencies

- package.json
The previous patch version of NPM was vulnerable by CWE-400, so I am just updating it to the latest patch version that resolved the security issue.
> fix(deps): updating npm dependency for CWE-400

- package-lock.json
- package.json
- test/helpers/config.yaml
- test/helpers/npm-registry.js
- test/prepare.test.js
I updated npm from v6 to v7. Reading the blogposts there shouldn't be any breaking changes, at least not in the functionality that semantic-release uses.
One test failed, but it was testing npm internal stuff about formating of package.json, so I removed it. (npm v7 does seem to preserve whatever formatting is in the file and just replace the version.) Hope that is okay?
> feat: Use npm v7

- README.md
- lib/get-registry.js
- test/get-registry.test.js
Previously NPM_CONFIG_USERCONFIG was only used for getting the auth token and not used for actually getting the registry from .npmrc.
Fixes #349
> fix: use `NPM_CONFIG_USERCONFIG` in get-registry to match auth

- README.md
Even though the example shows
```json
{
"scripts": {
"postversion": "cp -r package.json .. && cp -r npm-shrinkwrap.json .."
}
}
```
The description above it mentions using `postpublish` instead. I used `postpublish` in my workflow and ran into an issue where this hook is triggered _after_ [@semantic-release/git](https://github.com/semantic-release/git) determined what files to commit.
My exact situation was explained from the [FAQ](https://github.com/semantic-release/semantic-release/blob/master/docs/support/FAQ.md#how-can-i-use-a-npm-build-script-that-requires-the-packagejsons-version-) section, so I'm hoping to update the docs here.
> docs: update README description to match code example

- lib/add-channel.js
- lib/prepare.js
- lib/publish.js
- lib/verify-auth.js
relates #434, #270 
alternative #444
From execa@2.0.0, `preferLocal` is set to `false` by default. The plugin uses `^5.0.0` now.
#177, 2 Jul 2019, execa 1.0.0 → 2.0.2
https://github.com/sindresorhus/execa/releases/tag/v2.0.0
sindresorhus/execa#314
sindresorhus/execa@eb22ff7
> fix: add `preferLocal` option to allow execa to use local npm version

- README.md
Just came across this minor typography error.
> docs(readme): removed a duplicated word

- lib/prepare.js
> fix: add missed `preferLocal` option for execa call

- index.js
- lib/add-channel.js
- lib/prepare.js
- lib/publish.js
- lib/verify-auth.js
- package-lock.json
- package.json
- test/get-pkg.test.js
- test/integration.test.js
- test/prepare.test.js
- test/set-npmrc-auth.test.js
this PR should be integrated with a normal merge since these are independent updates of various impacts rather than being a single atomic change
> upgrade dependencies that are now unblocked after the esm transition

- package-lock.json
- package.json
this is a breaking change to add to the list of breakages for this beta. using a normal merge already includes the token to consider as a breakage
before we decide to merge this though, i think this is a chance to consider https://github.com/semantic-release/semantic-release/pull/2670#discussion_r1070214972 first. the options to decide between, as i see them, are:
* merge this PR that raises the peer requirement to the first beta of core that supports loading esm plugins, promote the beta of core still depending on a beta of the npm plugin, then raise the peer again to v21 that has been promoted to stable, and finally promote the npm plugin to stable
* backport the support for loading esm plugins to v20 of core, update the peer requirement here to the v20 version that supports esm …
> raised the peer requirement for semantic-release

- package-lock.json
- package.json
BREAKING CHANGE: the direct dependency on npm has been upgraded to v9. details of breaking changes can be found at https://github.com/npm/cli/releases/tag/v9.0.0
> fix(deps): upgraded npm to v9

- README.md
Extending the npm provenance section to be more helpful and provide complete example.
CI/CD pipeline failed and required digging into the issue log to find out other permissions are also needed to release a GitHub version, etc.
Updates the npm provenance section with copy/paste working example of YAML code that helps developers not fall into missing permission problems when wanting to enable the feature.
> docs(provenance): make the provenance details easier to consume

- package-lock.json
- package.json
- test/helpers/npm-registry.js
this uses the technique for waiting for the pull to complete [from the dockerode readme](https://github.com/apocas/dockerode/tree/edf29ccb2c2c7bfcdd1cf3cacbe861bd0f4bc87a#helper-functions) and gets rid of our dependence on get-stream
> test(integration): properly waited for the image pull to complete

- package-lock.json
- package.json
closes semantic-release/semantic-release#3202
even though our existing range allowed anyone to update as soon as the new `npm` version was available, this will encourage being on a version that does not report the `ip` vulnerability a bit more forcefully.
> fix(deps): raised the minimum accepted range of npm to v10.5.0

- .github/workflows/test.yml
- package-lock.json
- package.json
- test/helpers/npm-registry.js
- test/integration.test.js
* node v18 and v19 are no longer supported
* `exports` has been defined, which prevents access to private apis (which arent intended for consumption anyway)
> [!NOTE]
this PR contains multiple independent breaking changes, so it should not be squashed, as it is not atomic
unblocks https://github.com/semantic-release/npm/pull/764
> next major

- package-lock.json
- package.json
- closes https://github.com/semantic-release/npm/issues/966
- Before the release of [npm@10.9.3](https://github.com/npm/cli/releases/tag/v10.9.3), installing `@semantic-release/npm` reported a low severity vulnerability
- For such existing projects, `npm audit fix` continues to reports that the vulnerability cannot be fixed and refers to https://github.com/advisories/GHSA-v6h2-p8h4-qcjw (CVE-2025-5889 - brace-expansion Regular Expression Denial of Service vulnerability)
- Since the release of [npm@10.9.3](https://github.com/npm/cli/releases/tag/v10.9.3), a new installation of `@semantic-release/npm` reports no vulnerability
- Uninstalling and re-installing `semantic-release` and / or `@semantic-release/npm` also works around the issue
Update `npm` in package.json dependencies from …
> fix(deps): update npm to ^10.9.3

- README.md
<a href='https://hearts.dev/projects/3/users/babblebey'><img width='50' alt='' align='right' src='https://hearts.dev/projects/3/users/babblebey/tally.svg'></a>
This pull request makes a minor update to the build status badge in the `README.md` file to use the latest GitHub Actions workflow URL format.
* Updated the build status badge link to point to the current GitHub Actions workflow for tests.
> doc(README): fix CI build status badge
